### ISSUE TITLE
Swift 2 Branch - "Failed to build workspace Argo with scheme Argo-watchOS"

### ISSUE THREAD

**Issue by damianesteban** [rheinfabrik/Heimdall.swift#64] opened 2015-08-27 22:31 UTC
I'm attempting to install Heimdall from the Swift 2.0 branch via Carthage and I'm getting the following error:

    xcodebuild: error: Failed to build workspace Argo with scheme Argo-watchOS.
    Reason: The run destination My Mac is not valid for Running the scheme 'Argo-watchOS'.

Is anyone else getting this?

**Comment by felixjendrusch** [comment] 2015-10-20 10:44
Sorry for not responding earlier, @damianesteban! I cannot reproduce this, so I guess it was fixed.. closing this issue. Please let us know if you have any other issues or questions!

**Closed by felixjendrusch** 2015-10-20 10:44 UTC
